#+title: A Basic Implementation of Vector Commitments in LEAN4
#+author: Sati

* Introduction
** Commitment Schemes
   Let us imagine Alice and Bob want to play a game across the internet. Bob has a coin, and Alice needs to guess the result of Bob's coin flip. Normally, they cannot truly pay the game. If Alice reveals her guess before Bob reveals the result of the coin flip, Bob can lie about the result of the coin flip. If Alice reveals her guess after Bob reveals the result, then Alice can just lie about her guess.

   *Commitment schemes* are a way to get around this. The above game played using a commitment scheme works as follows:
   + Alice sends a *commitment* to Bob, that is generated using the guess, but does not reveal the guess itself.
   + Bob then *reveals* the result of the coin flip to Alice.
   + Alice then *reveals her guess*, along with a *proof*.
   + Bob uses *the guess, the proof, and the commitment* to *verify* that the guess was indeed what was committed to.
   
   More from [[https://en.wikipedia.org/wiki/Commitment_scheme][Wikipedia]]:
   #+begin_quote
   A *commitment scheme* is a cryptographic primitive that allows one to commit to a chosen value (or chosen statement) while keeping it hidden to others, with the ability to reveal the committed value later. Commitment schemes are designed so that /a party cannot change the value or statement after they have committed to it/: that is, commitment schemes are binding. Commitment schemes have important applications in a number of cryptographic protocols including *secure coin flipping, zero-knowledge proofs, and secure computation*. 
   #+end_quote
** Vector Commitment Schemes
   In [[https://eprint.iacr.org/2011/495.pdf][Vector Commitments and their Applications (D. Catalano and D. Fiore, Intl. Workshop on Public Key Cryptography, 2013)]], the authors introduce the notion of a *Vector Commitment Scheme*. Whereas a commitment scheme allows one to commit to a particular message, a vector commitment scheme allows one to commit to a *particular message at a particular position among a vector of messages*. More importantly, *neither the size of the commitment, nor the size of the proof, depends on the size of the vector*.
** This Project
   This project follows =Section 3.2= of the paper. It implements a vector commitment scheme as outlined using LEAN4 primitives, and also proves correctness theorems about them. The exact details and choices of representation (along with resulting compromises) are laid out below.
   
* Module-wise Project Overview
** [[file:VectorCommitmentsLean/RSA.lean][RSA.lean]]
*** Overview
    This file largely contains a proof of the RSA encryption algorithm, an almost direct portover of [[https://github.com/aronerben/lean-rsa][aronerben/lean-rsa]] from lean3/mathlib3 to lean4/mathlib4. Here is a short description of the actual changes:
    + Removed uses of all "global" variables.
    + Changed functions enc and dec to take public parameter "N" instead of accepting prime numbers p and q directly (as that would kind of defeat the whole point).
    + Introduced an incomplete definition of "RSA Adversary" as discussed in the paper.
    Everything is represented as a natural number. The implementation of the module turned out to be a bit eager, because despite the paper referencing RSA, it does not actually use RSA directly.
*** Lemmas, Theorems, Structures, and Functions
    + mod_pow_mod - ((a % n) ^ b) % n = (a ^ b) % n
    + mul_mod_right_distrib - (a * b) % n = ((a % n) * (b % n)) % n
    + enc - RSA encryption function, takes in a message, public key, and N to give an encrypted message
    + dec - RSA decryption function, takes in an encrypted message, private key, and N to give back an encrypted message
    + mul_coprime_or_coprime_and - If p and q are primes, then for any natural number n, then either both p and q are coprime to n, or atleast one isn't coprime.
    + dec_undoes_enc - Under the standard conditions required by RSA key generation, the message produced by encrypting and then decrypting a message produces the same message.
    + RSA_Adversary - An RSA_Adversary is a function =f= such that (f N e z) ^ e = z % N for all choices of N, e, z. This notion does not capture the Probabilistic Polynomial Time adversary as put forth in the paper.
** [[file:VectorCommitmentsLean/Basic.lean][Basic.lean]]
*** Overview
    This file implements a Vector Commitment Scheme as defined by paper, and proves *correctness*. 
*** Lemmas, Theorems, Structures, and Functions
    + FixedArray q - A LEAN Array, along with a proof that its size is q.
    + PublicParameters q - We use FixedArrays to represent the set of values for e and for S.
    + KeyGen - In the paper, KeyGen is supposed to "generate" two random prime numbers, along with other things. We choose to take them as input. KeyGen also takes in as hypotheses other proofs, that serve to ensure that the generated Public Parameters are valid.
    + Commitment, Open, Verify, Update, ProofUpdate - Work pretty much exactly as in the paper. Whenever they take an index as an input, they also take a proof stating that the index is within the bounds of the arrays.
    + fin_prod_factor_out - A lemma that is used in the proof of prod_is_perfect_power.
    + fin_prod_split - ∏ x : Fin q, f x = f i * ∏ x : Fin q, if x = i then 1 else f x
    + prod_is_perfect_power - In the vector commitment scheme, there are quite a few times where it is required to take the root of specific terms, with these specific terms having a common structure. This is used to show that whenever we take a root, we only take it for a term that is a perfect power wrt to the Root. (This is largely necessary because of how we choose to represent everything with natural numbers, and because we use the floorRoot function which is currently only implemented for natural numbers.)
    + mul_mod_pow_mod - (A * (B % N) ^ n) % N = (A * B ^ n) % N
    + if_neg_rewrite - Lemma that ended up not being used. Was supposed to help rewrite if conditionals.
    + normal_correctness - If a message is originally in a vector, then the commitment generated by Commitment and the proof generated by Proof will be valid for the Verify procedure.
    + update_correctness - If a message in a position is modified, then all the newly generated proofs and the newly generated commitment are valid wrt Verify.
    + VC_Adversary - A function that, given the public parameters, generates a commitment, along with two different messages and proofs, that are both valid at the same position. Again, this notion does not capture the Probabilistic Polynomial Time adversary put forth in the paper.
    + vc_secure - If we have a VC_Adversary, we have an RSA_Adversary ie. breaking the vector commitment scheme is atleast as difficult as breaking RSA encryption. A sensible proof for this would involve
      + Enhancing the VC_Adversary and RSA_Adversary representations themselves to better capture the required behaviour.
      + Proving all the external theorems that the proof from the paper relies upon.
* Possible Improvements
** Proof Automation
   Given the use of the conv tactic, it'd be of interest to develop proof automation that just possibly takes a theorem and a hypothesis/goal and rewrites where it can. (Note: For some reason, rw does not always directly work, LEAN often complains about it having the "wrong motive".)
** Proper Security Proofs
   Using the primitives presented in [[https://eprint.iacr.org/2025/1700.pdf][Computationally-Sound Symbolic Cryptography in Lean]], we may be able to actually flesh out the proof of the security of the scheme.
